/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Facturas_enp;

import com.itextpdf.text.pdf.PdfName;
import com.toedter.calendar.JDateChooser;
import conexion.conexion_bdd;
import java.awt.image.BufferedImage;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import javax.swing.DefaultComboBoxModel;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author ismael
 */
public class seleccionarmesreporte extends javax.swing.JFrame {
String fechainicio, fechafinal;
conexion.conexion_bdd cb = new conexion_bdd();
Connection con = cb.conectar_a_la_bdd();
    /** Creates new form seleccionarmesreporte */
    public seleccionarmesreporte() {
        initComponents();
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        fechainicio_jdc = new com.toedter.calendar.JDateChooser();
        fechafinal_jdc = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("REPORTEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CANCELAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        fechainicio_jdc.setDateFormatString("dd/MM/yyyy");

        fechafinal_jdc.setDateFormatString("dd/MM/yyyy");

        jLabel1.setText("Fecha de inicio");

        jLabel2.setText("Fecha Final");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(fechainicio_jdc, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(fechafinal_jdc, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fechainicio_jdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fechafinal_jdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //variables tipo date que obtienen los datos del jdc y los convierten a tipo date en el formato original            
        Date fechain = fechainicio_jdc.getDate();
        Date fechafin = fechafinal_jdc.getDate();
        //obtenemos los valores del date para poder convertirlos en tipo fecha de mysql
        long a = fechain.getTime();
        long b = fechafin.getTime();
        //creamos una entrada de cadenas desde el archivo a del reporte jxrml
        
//new FileInputStream("src\\Facturas_enp\\reporte.jrxml");
//convertimos los dates anteriores en date para mysql
java.sql.Date p1 = new java.sql.Date(a);
java.sql.Date p2 = new java.sql.Date(b);
//tambien los guardo en un string para comprobar que esten correctos
String fecha1 = String.valueOf(p1);
String fecha2 = String.valueOf(p2);
//aqui los imprimo
System.out.println(fecha1);
System.out.println(fecha2);

//creamos la instancia que guarda y enviara los parametros al reporte de la
//fechas between
Map parametros = new HashMap();
//asigno los valores de los parametros de las dos fechas que filtraran el reporte
parametros.put("desde",fecha1);
parametros.put("hasta",fecha2);


        try {
            JasperReport jr = (JasperReport) JRLoader.loadObject(getClass().getResource("/Facturas_enp/reporte.jasper"));
            JasperPrint jp = JasperFillManager.fillReport(jr,parametros,con);
            JasperViewer jw = new JasperViewer(jp);
            jw.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

 public void cargarmeses(){
     DefaultComboBoxModel cbmodel = new DefaultComboBoxModel();
     
     cbmodel.addElement("ENERO");
     cbmodel.addElement("FEBRERO");
     cbmodel.addElement("MARZO");
     cbmodel.addElement("ABRIL");
     cbmodel.addElement("MAYO");
     cbmodel.addElement("JUNIO");
     cbmodel.addElement("JULIO");
     cbmodel.addElement("AGOSTO");
     cbmodel.addElement("SEPTIEMBRE");
     cbmodel.addElement("OCTUBRE");
     cbmodel.addElement("DICIEMBRE");
     
     
     
 
 }   
    
 public void consultaconmes(){
 
     String enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre;
     String octubre,noviembre,diciembre;
     
     enero = "select factura, fecha, nombre,ficha,medicamento,cantidad,precio,total "
     + "from factura_sistema where fecha between '01/01/2019' and '31/01/2019' order by factura asc;";
     
     febrero = "select factura, fecha, nombre,ficha,medicamento,cantidad,precio,total "
+ "from factura_sistema where fecha between '01/02/2019' and '29/02/2019' order by factura asc;";
     
     marzo = "select factura, fecha, nombre,ficha,medicamento,cantidad,precio,total "
+ "from factura_sistema where fecha between '01/03/2019' and '31/03/2019' order by factura asc;";
     
     abril = "select factura, fecha, nombre,ficha,medicamento,cantidad,precio,total "
+ "from factura_sistema where fecha between '01/04/2019' and '30/04/2019' order by factura asc;";
     
     mayo = "select factura, fecha, nombre,ficha,medicamento,cantidad,precio,total "
+ "from factura_sistema where fecha between '01/05/2019' and '31/05/2019' order by factura asc;";
     
     junio = "select factura, fecha, nombre,ficha,medicamento,cantidad,precio,total from "
+ "factura_sistema where fecha between '01/06/2019' and '30/06/2019' order by factura asc;";
     
     julio = "select factura, fecha, nombre,ficha,medicamento,cantidad,precio,total "
+ "from factura_sistema where fecha between '01/07/2019' and '31/07/2019' order by factura asc;";
     
     agosto = "select factura, fecha, nombre,ficha,medicamento,cantidad,precio,total "
+ "from factura_sistema where fecha between '01/08/2019' and '31/08/2019' order by factura asc;";
     
     
 
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(seleccionarmesreporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(seleccionarmesreporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(seleccionarmesreporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(seleccionarmesreporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new seleccionarmesreporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser fechafinal_jdc;
    private com.toedter.calendar.JDateChooser fechainicio_jdc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
